#Binary folder location
binaries = "bin"

# Add pre-requirement libraries
# libs = socket?, threads? etc
# liker stuff as well...

#placeholder for all
args:
	@echo "specify a command!";

#Create binaries directory
binary:
	@if [ ! -d $(binaries) ]; then \
		mkdir $(binaries); \
	fi

#Compile whole project
all:


#Clean binaries folder
clean:
	@rm -f $(binaries)/*;
